// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGephRF0hCuL0wOrhDXbD3Fr3YEN30YiU',
    appId: '1:131205636358:web:1189edd01ea904d9e6be87',
    messagingSenderId: '131205636358',
    projectId: 'swiftidate-cdff0',
    authDomain: 'swiftidate-cdff0.firebaseapp.com',
    databaseURL: 'https://swiftidate-cdff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftidate-cdff0.appspot.com',
    measurementId: 'G-R2NTX4WYKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrrr1OffYGMMU5zcGuSa6Ax3MLufb8A2A',
    appId: '1:131205636358:android:7386f9fd8af5a703e6be87',
    messagingSenderId: '131205636358',
    projectId: 'swiftidate-cdff0',
    databaseURL: 'https://swiftidate-cdff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftidate-cdff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Wo88mYn8FjYwFHkDG2zvsbQfZR-Zwv0',
    appId: '1:131205636358:ios:dbb6b574b8684043e6be87',
    messagingSenderId: '131205636358',
    projectId: 'swiftidate-cdff0',
    databaseURL: 'https://swiftidate-cdff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftidate-cdff0.appspot.com',
    iosBundleId: 'com.example.swiftidate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Wo88mYn8FjYwFHkDG2zvsbQfZR-Zwv0',
    appId: '1:131205636358:ios:dbb6b574b8684043e6be87',
    messagingSenderId: '131205636358',
    projectId: 'swiftidate-cdff0',
    databaseURL: 'https://swiftidate-cdff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftidate-cdff0.appspot.com',
    iosBundleId: 'com.example.swiftidate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGephRF0hCuL0wOrhDXbD3Fr3YEN30YiU',
    appId: '1:131205636358:web:1189edd01ea904d9e6be87',
    messagingSenderId: '131205636358',
    projectId: 'swiftidate-cdff0',
    authDomain: 'swiftidate-cdff0.firebaseapp.com',
    databaseURL: 'https://swiftidate-cdff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftidate-cdff0.appspot.com',
    measurementId: 'G-R2NTX4WYKG',
  );
}
